

# 错误码
ERROR_EMPTY_EMAIL_OR_PASSWORD = 1040
ERROR_EMPTY_EMAIL_OR_PASSWORD_MESSAGE = '用户名或密码不能为空'

# 业务错误码
ERROR_USER_EXIST = 1000
ERROR_USER_EXIST_MESSAGE = '用户已经存在'

# 全局错误码
ERROR_ARGUMENT = 30
ERROR_ARGUMENT_MESSAGE = '参数错误' 

# 用户不存在
ERROR_USER_NOT_EXIST = 1010
ERROR_USER_NOT_EXIST_MESSAGE = '用户不存在'

ERROR_USERNAME_OR_PASSWORD = 1030
ERROR_USERNAME_OR_PASSWORD_MESSAGE = '用户名或密码失败'